### ISSUE TITLE
Sentry app issue - NullPointerException by onConnectionFailed

### ISSUE THREAD

**Issue by chico** [OttoDIY/OttoDIYApp#48]
Fix the following exception that is happening on [Sentry](https://sentry.io/organizations/otto-diy/issues/1410969089/?project=1867816&query=is%3Aunresolved&statsPeriod=30d):
java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
    at com.facebook.react.bridge.PromiseImpl.reject(PromiseImpl.java:232)
    at com.facebook.react.bridge.PromiseImpl.reject(PromiseImpl.java:105)
    at com.rusel.RCTBluetoothSerial.RCTBluetoothSerialModule.onConnectionFailed(RCTBluetoothSerialModule.java:449)
    at com.rusel.RCTBluetoothSerial.RCTBluetoothSerialService.connectionFailed(RCTBluetoothSerialService.java:157)
    at com.rusel.RCTBluetoothSerial.RCTBluetoothSerialService.access$300(RCTBluetoothSerialService.java:23)
    at com.rusel.RCTBluetoothSerial.RCTBluetoothSerialService$ConnectThread.run(RCTBluetoothSerialService.java:245)

**Comment by chico** [comment]
Fixed by https://github.com/OttoDIY/OttoDIYApp/pull/49
